"use client";

import Image from "next/image";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { ArrowLeft, ArrowRight, Check, ChevronDown, CircleCheck, Heart, Mail, MapPin, Minus, Package, PackageCheck, Phone, Plus, Search, ShieldCheck, Truck, User } from "lucide-react";
import { catalog, demoOrder } from "@/data/catalog";
import { faqs } from "@/data/store";
import { PageHero, SiteShell } from "./site-shell";
import { ProductCard } from "./product-card";

export function ShopPage() {
  const [sort, setSort] = useState("Featured");
  return <SiteShell><PageHero eyebrow="The collection" title="Fewer things. Better chosen." copy="Thoughtfully designed objects that make everyday focus feel calmer." /><section className="shopToolbar sectionShell"><span>{catalog.length} products</span><div><button>Lighting</button><button>Workspace</button><label>Sort by <select value={sort} onChange={e => setSort(e.target.value)}><option>Featured</option><option>Price: low to high</option><option>Newest</option></select></label></div></section><section className="productGrid sectionShell">{catalog.map(item => <ProductCard key={item.slug} product={item} />)}</section><section className="collectionNote sectionShell"><span>Our approach</span><h2>We make room for the things that earn it.</h2><p>Every Woxly object begins with a small everyday frustration and ends only when the solution feels useful, durable and quietly beautiful.</p></section></SiteShell>;
}

export function SearchPage() {
  const [query, setQuery] = useState("lamp");
  const results = catalog.filter(item => item.name.toLowerCase().includes(query.toLowerCase()));
  return <SiteShell><PageHero eyebrow="Find what you need" title="Search Woxly" /><section className="searchPanel sectionShell"><Search /><input aria-label="Search products" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search products, guides and stories"/><button>Search</button></section><section className="searchSummary sectionShell"><p>{results.length} results for “{query || "all products"}”</p></section><section className="productGrid sectionShell">{results.map(item => <ProductCard key={item.slug} product={item} />)}{results.length === 0 && <div className="emptyState"><Search /><h2>No results yet</h2><p>Try a broader search or explore the complete collection.</p><Link href="/shop">Browse all products</Link></div>}</section></SiteShell>;
}

export function CartPage() {
  const [quantity, setQuantity] = useState(1);
  return <SiteShell><PageHero eyebrow="Your selection" title="Shopping bag" /><section className="cartPage sectionShell"><div className="cartList"><div className="shippingProgress"><CircleCheck /> You have free delivery <i><b /></i></div><article className="cartLine"><div className="cartLineImage"><Image src="/images/sol-hero.png" alt="Sol Focus Lamp" fill /></div><div><small>Lighting</small><h2>Sol Focus Lamp</h2><p>Warm sand</p><div className="quantity"><button onClick={() => setQuantity(Math.max(1, quantity - 1))} aria-label="Decrease quantity"><Minus /></button><span>{quantity}</span><button onClick={() => setQuantity(quantity + 1)} aria-label="Increase quantity"><Plus /></button></div></div><div><strong>₹{(3499 * quantity).toLocaleString("en-IN")}</strong><button className="textButton">Remove</button></div></article></div><aside className="orderSummary"><h2>Order summary</h2><div><span>Subtotal</span><strong>₹{(3499 * quantity).toLocaleString("en-IN")}</strong></div><div><span>Delivery</span><strong>Free</strong></div><div className="summaryTotal"><span>Total <small>incl. taxes</small></span><strong>₹{(3499 * quantity).toLocaleString("en-IN")}</strong></div><Link className="checkoutButton" href="/checkout">Continue to checkout <ArrowRight /></Link><p><ShieldCheck /> Secure checkout · 30-day returns</p></aside></section><section className="cartHelp sectionShell"><PackageCheck /><div><strong>Need help with your order?</strong><p>Our product team is available Monday–Saturday.</p></div><Link href="/contact">Contact us</Link></section></SiteShell>;
}

export function CheckoutPage() {
  return <SiteShell><section className="checkoutPage sectionShell"><div className="checkoutMain"><Link href="/cart" className="backLink"><ArrowLeft /> Back to bag</Link><span className="sectionKicker">Secure checkout</span><h1>Where should we send it?</h1><CheckoutForm /></div><aside className="checkoutSummary"><div className="checkoutProduct"><Image src="/images/sol-hero.png" alt="Sol Focus Lamp" width={90} height={110}/><div><h3>Sol Focus Lamp</h3><p>Warm sand · Qty 1</p></div><strong>₹3,499</strong></div><div><span>Subtotal</span><strong>₹3,499</strong></div><div><span>Delivery</span><strong>Free</strong></div><div className="summaryTotal"><span>Total</span><strong>₹3,499</strong></div><div className="secureNote"><ShieldCheck /> Your payment details are encrypted and secure.</div></aside></section></SiteShell>;
}

function CheckoutForm() {
  const [payment, setPayment] = useState("upi");
  return <form className="checkoutForm" onSubmit={e => e.preventDefault()}><section><div className="formHeading"><b>1</b><h2>Contact</h2></div><label>Email address<input type="email" placeholder="you@example.com" required /></label><label className="checkLabel"><input type="checkbox" /> Send order updates on WhatsApp</label></section><section><div className="formHeading"><b>2</b><h2>Delivery address</h2></div><div className="formGrid"><label>First name<input required /></label><label>Last name<input required /></label><label className="wide">Address<input required /></label><label>City<input required /></label><label>Pincode<input inputMode="numeric" maxLength={6} required /></label><label>State<select><option>Karnataka</option><option>Maharashtra</option><option>Delhi</option></select></label><label>Phone<input type="tel" required /></label></div></section><section><div className="formHeading"><b>3</b><h2>Payment</h2></div><div className="paymentOptions">{[["upi", "UPI / QR"], ["card", "Credit or debit card"], ["cod", "Cash on delivery"]].map(([id,label]) => <label key={id} className={payment === id ? "active" : ""}><input type="radio" name="payment" checked={payment === id} onChange={() => setPayment(id)} /><span>{label}</span><small>{id === "cod" ? "Pay when your order arrives" : "Secure online payment"}</small></label>)}</div></section><Link href="/order-success" className="placeOrderButton">Place order · ₹3,499 <ArrowRight /></Link><p className="formLegal">By placing your order, you agree to our <Link href="/terms">terms</Link> and <Link href="/privacy-policy">privacy policy</Link>.</p></form>;
}

export function OrderSuccessPage() {
  return <SiteShell><section className="successPage sectionShell"><div className="successIcon"><Check /></div><span className="sectionKicker">Order confirmed</span><h1>Thank you. It’s on its way.</h1><p>We sent a confirmation to you@example.com. Your order is being prepared with care.</p><div className="successCard"><div><small>Order number</small><strong>{demoOrder.number}</strong></div><div><small>Estimated delivery</small><strong>{demoOrder.delivery}</strong></div><div><small>Total</small><strong>₹3,499</strong></div></div><div className="successActions"><Link href="/track-order">Track your order <ArrowRight /></Link><Link href="/shop">Continue shopping</Link></div></section></SiteShell>;
}

export function TrackOrderPage() {
  const [tracked, setTracked] = useState(false);
  return <SiteShell><PageHero eyebrow="Order updates" title="Track your order" copy="Enter your order number and email address to see the latest delivery status." /><section className="trackLayout sectionShell"><form className="trackForm" onSubmit={(e: FormEvent) => { e.preventDefault(); setTracked(true); }}><label>Order number<input defaultValue="WX-10482" required /></label><label>Email address<input type="email" defaultValue="you@example.com" required /></label><button>Track order <ArrowRight /></button></form>{tracked ? <OrderTracker /> : <div className="trackAside"><Package /><h2>Your delivery, clearly tracked.</h2><p>We’ll show every step from our studio to your door.</p></div>}</section></SiteShell>;
}

function OrderTracker() { return <div className="orderTracker"><div className="trackerTop"><span><Truck /></span><div><small>{demoOrder.number}</small><h2>{demoOrder.status}</h2><p>Estimated delivery {demoOrder.delivery}</p></div></div><ol><li className="done"><i><Check /></i><div><strong>Order confirmed</strong><small>14 Sep · 10:24 AM</small></div></li><li className="done"><i><Check /></i><div><strong>Shipped from our studio</strong><small>16 Sep · 6:40 PM</small></div></li><li className="active"><i><Truck /></i><div><strong>In transit</strong><small>Arrived at Bengaluru facility</small></div></li><li><i><PackageCheck /></i><div><strong>Delivered</strong><small>Expected by 21 Sep</small></div></li></ol></div>; }

export function AuthPage({ mode }: { mode: "login" | "signup" }) {
  const login = mode === "login";
  return <SiteShell><section className="authPage"><div className="authVisual"><Image src="/images/sol-lifestyle.png" alt="A calm workspace" fill/><div><span>Woxly membership</span><h2>Your orders, saved favourites and better spaces—all together.</h2></div></div><div className="authPanel"><div><span className="sectionKicker">{login ? "Welcome back" : "Join Woxly"}</span><h1>{login ? "Sign in to your account" : "Create your account"}</h1><p>{login ? "Access orders, tracking and saved products." : "Save favourites and make checkout quicker."}</p><form onSubmit={e => e.preventDefault()}>{!login && <label>Full name<input required placeholder="Your name" /></label>}<label>Email address<input type="email" required placeholder="you@example.com" /></label><label>Password<input type="password" required placeholder="At least 8 characters" /></label>{login && <div className="formSplit"><label className="checkLabel"><input type="checkbox" /> Remember me</label><Link href="#">Forgot password?</Link></div>}<Link className="authButton" href="/account">{login ? "Sign in" : "Create account"}<ArrowRight /></Link></form><div className="authSwitch">{login ? "New to Woxly?" : "Already have an account?"} <Link href={login ? "/signup" : "/login"}>{login ? "Create account" : "Sign in"}</Link></div></div></div></section></SiteShell>;
}

export function AccountPage() {
  return <SiteShell><section className="accountHeader sectionShell"><div><span className="sectionKicker">My Woxly</span><h1>Good morning, Haris.</h1><p>Manage your orders, details and saved pieces.</p></div><Link href="/">Sign out</Link></section><section className="accountGrid sectionShell"><Link href="/account/orders"><Package /><span><strong>My orders</strong><small>View and track your purchases</small></span><ArrowRight /></Link><Link href="/account/profile"><User /><span><strong>Profile</strong><small>Personal details and addresses</small></span><ArrowRight /></Link><Link href="/wishlist"><Heart /><span><strong>Wishlist</strong><small>3 saved products</small></span><ArrowRight /></Link><Link href="/contact"><Mail /><span><strong>Support</strong><small>We’re here when you need us</small></span><ArrowRight /></Link></section><section className="recentOrder sectionShell"><div className="sectionTitle"><div><span className="sectionKicker">Latest purchase</span><h2>Recent order</h2></div><Link href="/account/orders">View all orders</Link></div><OrderRow /></section></SiteShell>;
}

export function ProfilePage() {
  return <SiteShell><AccountNav active="profile" /><section className="profilePage sectionShell"><div><span className="sectionKicker">Account settings</span><h1>Your profile</h1><p>Keep your contact and delivery details up to date.</p></div><form onSubmit={e => e.preventDefault()}><div className="formGrid"><label>First name<input defaultValue="Haris" /></label><label>Last name<input defaultValue="K" /></label><label className="wide">Email address<input type="email" defaultValue="you@example.com" /></label><label className="wide">Phone number<input type="tel" defaultValue="+91 98765 43210" /></label></div><h2>Default delivery address</h2><div className="formGrid"><label className="wide">Address<input defaultValue="24, Residency Road" /></label><label>City<input defaultValue="Bengaluru" /></label><label>Pincode<input defaultValue="560001" /></label></div><button>Save changes</button></form></section></SiteShell>;
}

function AccountNav({ active }: { active: string }) { return <nav className="accountNav sectionShell"><Link className={active === "overview" ? "active" : ""} href="/account">Overview</Link><Link className={active === "orders" ? "active" : ""} href="/account/orders">Orders</Link><Link className={active === "profile" ? "active" : ""} href="/account/profile">Profile</Link><Link className={active === "wishlist" ? "active" : ""} href="/wishlist">Wishlist</Link></nav>; }

function OrderRow() { return <article className="orderRow"><div className="orderThumb"><Image src="/images/sol-hero.png" alt="" fill /></div><div><small>Order {demoOrder.number}</small><h3>Sol Focus Lamp</h3><p>{demoOrder.date} · ₹3,499</p></div><span className="statusBadge"><i />{demoOrder.status}</span><Link href={`/account/orders/${demoOrder.number}`}>View order <ArrowRight /></Link></article>; }

export function OrdersPage() { return <SiteShell><AccountNav active="orders" /><section className="ordersPage sectionShell"><span className="sectionKicker">Purchase history</span><h1>My orders</h1><div className="orderFilters"><button className="active">All orders</button><button>In progress</button><button>Delivered</button></div><OrderRow /><OrderRow /></section></SiteShell>; }

export function OrderDetailsPage() { return <SiteShell><AccountNav active="orders" /><section className="orderDetails sectionShell"><Link className="backLink" href="/account/orders"><ArrowLeft /> Back to orders</Link><div className="orderDetailsHead"><div><span className="sectionKicker">Order {demoOrder.number}</span><h1>{demoOrder.status}</h1><p>Placed on {demoOrder.date}</p></div><Link href="/track-order">Track delivery <ArrowRight /></Link></div><div className="orderDetailsGrid"><div><OrderRow /><div className="orderTimeline"><h2>Order progress</h2><OrderTracker /></div></div><aside className="detailsAside"><section><h3>Delivery address</h3><p>Haris K<br/>24, Residency Road<br/>Bengaluru 560001<br/>+91 98765 43210</p></section><section><h3>Payment</h3><p>UPI · Paid<br/>Transaction ending 2381</p></section><section><h3>Summary</h3><div><span>Subtotal</span><b>₹3,499</b></div><div><span>Delivery</span><b>Free</b></div><div><span>Total</span><b>₹3,499</b></div></section></aside></div></section></SiteShell>; }

export function WishlistPage() { return <SiteShell><AccountNav active="wishlist" /><PageHero eyebrow="Saved for later" title="Your wishlist" copy="A quiet corner for the pieces you want to come back to."/><section className="productGrid sectionShell">{catalog.map(item => <ProductCard key={item.slug} product={item} />)}</section></SiteShell>; }

export function BlogPage() { const posts = [{title:"The quiet science of better task lighting",tag:"Better work",image:"/images/sol-lifestyle.png"},{title:"How to make a small desk feel expansive",tag:"Space",image:"/images/sol-hero.png"},{title:"A designer’s guide to warmer evenings",tag:"Rituals",image:"/images/sol-detail.png"}]; return <SiteShell><PageHero eyebrow="The Woxly journal" title="Notes for brighter spaces." copy="Design, rituals and practical ideas for doing your best work without losing your calm."/><section className="featuredPost sectionShell"><div><Image src="/images/sol-lifestyle.png" alt="A warmly lit desk" fill /></div><article><span>Featured · 8 min read</span><h2>Why good light changes more than what you see.</h2><p>We spoke with workspace designers about attention, atmosphere and the small choices that make a room work harder.</p><Link href="#">Read the story <ArrowRight /></Link></article></section><section className="postGrid sectionShell">{posts.map(post => <article key={post.title}><div><Image src={post.image} alt="" fill /></div><span>{post.tag} · 5 min read</span><h3>{post.title}</h3><Link href="#">Read article</Link></article>)}</section></SiteShell>; }

export function AboutPage() { return <SiteShell><section className="aboutHero"><Image src="/images/sol-lifestyle.png" alt="The Woxly design approach" fill/><div><span>Our story</span><h1>Useful should still feel beautiful.</h1></div></section><section className="aboutIntro sectionShell"><span className="sectionKicker">Woxly, Bengaluru</span><h2>We design everyday objects for people who notice the details.</h2><p>Woxly began with a simple belief: the products closest to us should reduce noise, not add to it. We focus on fewer objects, honest materials and forms that settle naturally into real homes.</p></section><section className="valuesGrid sectionShell"><article><b>01</b><h3>Purpose first</h3><p>Every detail begins with a job to do—not a trend to follow.</p></article><article><b>02</b><h3>Made to stay</h3><p>We choose durable materials and repairable thinking wherever possible.</p></article><article><b>03</b><h3>Calm by design</h3><p>Quiet forms, intuitive controls and no unnecessary complexity.</p></article></section></SiteShell>; }

export function ContactPage() { return <SiteShell><PageHero eyebrow="We’re listening" title="How can we help?" copy="Questions about a product, delivery or an existing order? Our small team will get back to you within one business day."/><section className="contactGrid sectionShell"><div className="contactMethods"><article><Mail/><div><h3>Email us</h3><p>hello@woxly.com</p><small>Replies within one business day</small></div></article><article><Phone/><div><h3>Call us</h3><p>+91 80 4567 8900</p><small>Mon–Sat, 10am–6pm IST</small></div></article><article><MapPin/><div><h3>Studio</h3><p>Indiranagar, Bengaluru</p><small>Visits by appointment</small></div></article></div><form className="contactForm" onSubmit={e => e.preventDefault()}><label>Name<input required /></label><label>Email<input type="email" required /></label><label>What can we help with?<select><option>Product question</option><option>Order support</option><option>Returns</option><option>Press and partnerships</option></select></label><label>Message<textarea rows={6} required /></label><button>Send message <ArrowRight /></button></form></section></SiteShell>; }

export function FAQPage() { return <SiteShell><PageHero eyebrow="Help centre" title="Questions, answered." copy="Everything you need to know about products, delivery, returns and care."/><section className="faqPage sectionShell"><nav><a href="#products">Products</a><a href="#orders">Orders</a><a href="#delivery">Delivery</a><a href="#returns">Returns</a></nav><div><h2 id="products">Products</h2>{faqs.slice(0,3).map((f,i)=><details key={f.question} open={i===0}><summary>{f.question}<ChevronDown/></summary><p>{f.answer}</p></details>)}<h2 id="orders">Orders & delivery</h2>{faqs.slice(3).map(f=><details key={f.question}><summary>{f.question}<ChevronDown/></summary><p>{f.answer}</p></details>)}</div></section></SiteShell>; }

export function PolicyPage({ type }: { type: "privacy" | "terms" | "shipping" | "returns" }) {
  const content = {
    privacy: { eyebrow:"Legal", title:"Privacy policy", intro:"How we collect, use and protect your personal information.", sections:[["Information we collect","We collect information you provide when placing an order, creating an account or contacting us. This may include your name, contact details, delivery address and order history."],["How we use information","We use your information to fulfil orders, provide support, improve the storefront and send marketing only when you have chosen to receive it."],["Your choices","You can request access, correction or deletion of eligible personal data by contacting privacy@woxly.com."],["Data security","We use reasonable administrative and technical safeguards. Payment details are processed by certified payment providers and are not stored by Woxly."]] },
    terms: { eyebrow:"Legal", title:"Terms & conditions", intro:"The terms that apply when you browse or purchase from Woxly.", sections:[["Using this website","By using this website, you agree to these terms and applicable laws. Product imagery and descriptions are provided as accurately as possible."],["Orders and pricing","Orders are accepted once payment is confirmed and stock is available. If a pricing or inventory error occurs, we will contact you before fulfilment."],["Intellectual property","Woxly branding, copy, imagery and product designs may not be reproduced without written permission."],["Liability","Nothing in these terms limits rights available to you under applicable consumer law."]] },
    shipping: { eyebrow:"Delivery", title:"Shipping & delivery", intro:"Clear timelines, careful packing and updates along the way.", sections:[["Processing","In-stock orders typically leave our studio within one business day. Orders placed on Sundays or public holidays are processed the following business day."],["Delivery estimates","Most Indian metro deliveries arrive within 3–5 business days. Remote locations may require 5–8 business days."],["Shipping charges","Standard shipping is complimentary across India. Any expedited option and its cost will be shown at checkout."],["Tracking","You will receive a tracking link by email or WhatsApp after dispatch. You can also use our Track Order page."]] },
    returns: { eyebrow:"Peace of mind", title:"Return & refund policy", intro:"If it is not right for your space, we will help make it right.", sections:[["30-day returns","Unused products in original packaging can be returned within 30 days of delivery. Contact us before sending an item back."],["Damaged items","Report transit damage within 48 hours with photos of the product and packaging so we can arrange a replacement."],["Refunds","Approved refunds are returned to the original payment method within 5–10 business days after inspection."],["Non-returnable items","Personalised items, gift cards and products marked final sale are not eligible unless they arrive damaged or defective."]] }
  }[type];
  return <SiteShell><PageHero eyebrow={content.eyebrow} title={content.title} copy={content.intro}/><section className="policyLayout sectionShell"><aside><span>Last updated</span><strong>17 September 2026</strong><Link href="/contact">Need help? Contact us</Link></aside><article>{content.sections.map(([heading,body],i)=><section key={heading}><span>0{i+1}</span><h2>{heading}</h2><p>{body}</p></section>)}</article></section></SiteShell>;
}
